

services:
  wb_control_service:
    container_name: wb_control_service
    image: http://registry/light_control:wb_control_service
    ports:
      - "8080:8080"

  recognition_service:
    container_name: recognition_service
    image: http://registry/light_control:recognition_service
    ports:
      - "8081:8081"

  frontend:
    container_name: frontend
    image: http://registry/light_control:nginx
    ports:
      - "80:80"
      - "443:443"
