

services:
  wb_control_service:
    container_name: wb_control_service
    build:
      context: wb_control_service
      dockerfile: Dockerfile
    restart: always
    environment:
      MQTT_IP_ADDR: "192.168.0.106"
      MQTT_PORT: 1883
    ports:
      - "8080:8080"

  recognition_service:
    container_name: recognition_service
    build:
      context: recognition_service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"

  frontend:
    container_name: frontend
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./nginx/public:/usr/share/nginx/static/
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8000:8000"
      - "443:443"
